apiVersion: metalkube.org/v1alpha1

kind: BareMetalHost
metadata:
  name: master-1
  annotations:
      kni.io/sdnNetworkMac: "0c:c4:7a:8e:ee:0c"
#     kni.io/sdnIPv4: "192.168.111.12"

spec:
  externallyProvisioned: true
  online: true
  hardwareProfile: "master"
  bmc:
    address: ipmi://10.19.110.10
    credentialsName: ha-lab-ipmi
  bootMACAddress: 0C:C4:7A:DB:A8:59

  