apiVersion: metalkube.org/v1alpha1

kind: BareMetalHost
metadata:
  name: master-0
  annotations:
      kni.io/sdnNetworkMac: "0c:c4:7a:19:6f:92"
#      kni.io/sdnIPv4: "192.168.111.11"

spec:
  externallyProvisioned: true
  online: true
  hardwareProfile: "master"
  bmc:
    address: ipmi://10.19.110.12
    credentialsName: ha-lab-ipmi
  bootMACAddress: 0C:C4:7A:DB:A9:93

  