apiVersion: metalkube.org/v1alpha1

kind: BareMetalHost
metadata:
  name: worker-1
  annotations:
    kni.io/sdnNetworkMac: "0c:c4:7a:19:6f:7e"
    kni.io/kernel: "assets/rhel_vmlinuz"
    kni.io/initrd: "assets/rhel_initrd.img"
    kni.io/kickstart: "http://${PROVISION_IP}:8080/assets/centos-rt-worker-kickstart.cfg"

spec:
  externallyProvisioned: true
  online: true
  hardwareProfile: "worker"
  bmc:
    address: ipmi://10.19.110.8
    credentialsName: ha-lab-ipmi
  bootMACAddress: 0C:C4:7A:DB:AC:03

